/*
 * BreathSense intentionally does not use Silicon Labs' autogenerated
 * sl_tflite_micro_init.cc interpreter/model.
 *
 * The application uses breathsense_inference_runtime.cc instead.
 * This empty hook satisfies the generated system initialization call.
 */
extern "C" void sl_tflite_micro_init(void)
{
  /* Intentionally empty. */
}
